# Generated by Django 5.2.7 on 2025-12-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
