# Generated by Django 5.2.7 on 2025-12-17 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_tasktable_taskrow_taskcolumn_taskcell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcolumn',
            name='table',
        ),
        migrations.RemoveField(
            model_name='taskrow',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tasktable',
            name='owner',
        ),
        migrations.DeleteModel(
            name='TaskCell',
        ),
        migrations.DeleteModel(
            name='TaskColumn',
        ),
        migrations.DeleteModel(
            name='TaskRow',
        ),
        migrations.DeleteModel(
            name='TaskTable',
        ),
    ]
